<?php

namespace chirag\Employee\Tests;

use chirag\Employee\EmployeeBaseServiceProvider;
use Orchestra\Testbench\Console\Kernel;

class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withFactories(__DIR__ . '/../database/factories');
        $this->loadLaravelMigrations(['--database' => 'peopleten']);
        $this->withoutMockingConsoleOutput();

    }

    /**
     * Get package providers.
     *
     * @param  \Illuminate\Foundation\Application  $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            EmployeeBaseServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'peopleten');
        $app['config']->set('database.connections.peopleten', [
            'driver' => 'mysql',
            'database' => 'peopleten',
            'host' => 'localhost',
            'port' => '3306',
            'username' => 'root',
            'password' => '',
        ]);
    }

    /**
     * Resolve application Console Kernel implementation.
     *
     * @param  \Illuminate\Foundation\Application  $app
     * @return void
     */
    protected function resolveApplicationConsoleKernel($app)
    {
        $app->singleton('Illuminate\Contracts\Console\Kernel', 'Orchestra\Testbench\Console\Kernel');
    }
}
